import { IRecipe } from "../../../../shared/types";

export const mockResponseSearch: IRecipe[] = [
  {
      "idMeal": 53071,
      "strMeal": "Beef Asado",
      "strDrinkAlternate": null,
      "strCategory": "Beef",
      "strArea": "Filipino",
      "strInstructions": "0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
      "strTags": "",
      "strYoutube": "https://www.youtube.com/watch?v=lNlK8DVhXXA",
      "strIngredient1": "Beef",
      "strIngredient2": "Beef Stock Concentrate",
      "strIngredient3": "Tomato Puree",
      "strIngredient4": "Water",
      "strIngredient5": "Soy Sauce",
      "strIngredient6": "White Wine Vinegar",
      "strIngredient7": "Pepper",
      "strIngredient8": "Bay Leaf",
      "strIngredient9": "Lemon",
      "strIngredient10": "Tomato Sauce",
      "strIngredient11": "Butter",
      "strIngredient12": "Olive Oil",
      "strIngredient13": "Onion",
      "strIngredient14": "Garlic",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1.5kg",
      "strMeasure2": "1",
      "strMeasure3": "8 ounces",
      "strMeasure4": "3 cups ",
      "strMeasure5": "6 tablespoons",
      "strMeasure6": "1 tbs",
      "strMeasure7": "2 tbs",
      "strMeasure8": "4",
      "strMeasure9": "1/2 ",
      "strMeasure10": "2 tbs",
      "strMeasure11": "3 tbs",
      "strMeasure12": "1/2 cup ",
      "strMeasure13": "1 chopped",
      "strMeasure14": "4 cloves",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://panlasangpinoy.com/beef-asado/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
  },
  {
      "idMeal": 52928,
      "strMeal": "BeaverTails",
      "strDrinkAlternate": null,
      "strCategory": "Dessert",
      "strArea": "Canadian",
      "strInstructions": "In the bowl of a stand mixer, add warm water, a big pinch of sugar and yeast. Allow to sit until frothy.\r\nInto the same bowl, add 1/2 cup sugar, warm milk, melted butter, eggs and salt, and whisk until combined.\r\nPlace a dough hook on the mixer, add the flour with the machine on, until a smooth but slightly sticky dough forms.\r\nPlace dough in a bowl, cover with plastic wrap, and allow to proof for 1 1/2 hours.\r\nCut dough into 12 pieces, and roll out into long oval-like shapes about 1/4 inch thick that resemble a beaver\u2019s tail.\r\nIn a large, deep pot, heat oil to 350 degrees. Gently place beavertail dough into hot oil and cook for 30 to 45 seconds on each side until golden brown.\r\nDrain on paper towels, and garnish as desired. Toss in cinnamon sugar, in white sugar with a squeeze of lemon, or with a generous slathering of Nutella and a handful of toasted almonds. Enjoy!",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg",
      "strTags": "Treat,Pudding,Speciality",
      "strYoutube": "https://www.youtube.com/watch?v=2G07UOqU2e8",
      "strIngredient1": "Water",
      "strIngredient2": "Yeast",
      "strIngredient3": "Sugar",
      "strIngredient4": "Milk",
      "strIngredient5": "Butter",
      "strIngredient6": "Eggs",
      "strIngredient7": "Salt",
      "strIngredient8": "Flour",
      "strIngredient9": "Oil",
      "strIngredient10": "Lemon",
      "strIngredient11": "Sugar",
      "strIngredient12": "Cinnamon",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1/2 cup ",
      "strMeasure2": "2 parts ",
      "strMeasure3": "1/2 cup ",
      "strMeasure4": "1/2 cup ",
      "strMeasure5": "6 tblsp",
      "strMeasure6": "2",
      "strMeasure7": "1 \u00bd tsp",
      "strMeasure8": "2-1/2 cups",
      "strMeasure9": "for frying",
      "strMeasure10": "garnish",
      "strMeasure11": "garnish",
      "strMeasure12": "garnish",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.tastemade.com/videos/beavertails",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
  }
]